### ISSUE TITLE
Numeric tokens fail to interpolate 

### ISSUE THREAD

**Issue by atomicpages** [erictooth/token2css#1]
Adding a token like:

```yml
foo:
  bar:
    margin-left: 0
```

fails because `.replace` is not on the `Number` object's prototype.
